import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/Layout'
import SideBar from '../components/dashboard/sideBar/sideBarAdmin'
import { DashboardProvider } from '../contexts/DashboardContext'
import { AuthProvider } from '../components/auth/AuthProvider'
import { LanguageProvider } from '../contexts/LanguageContext'

function MyApp({ Component, pageProps, router }) {
  const isDashboard = router.pathname.startsWith("/dashboard");

  return (
    <>
      <Head>
        <title>Stocker</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon"
         href="/img/logo80.webp" />
      </Head>
      
      <AuthProvider>
        <LanguageProvider>
          {isDashboard ? (
            <DashboardProvider>
              <SideBar>
                <Component {...pageProps} />
              </SideBar>
            </DashboardProvider>
          ) : (
            <Layout>
              <Component {...pageProps} />
            </Layout>
          )}
        </LanguageProvider>
      </AuthProvider>
    </>
  )
}

export default MyApp
